AllCops:
  TargetRubyVersion: 3.0
  SuggestExtensions: false
  NewCops: disable

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ParameterLists:
  Max: 15

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false
