module MacawFramework
  class Macaw
    @bind: String
    @cache: untyped
    @cached_methods: Hash[String, Array[String]]
    @config: Hash[String, untyped]
    @cron_runner: CronRunner
    @endpoints_to_cache: Array[String]
    @macaw_log: Logger?

    @prometheus: untyped
    @prometheus_middleware: untyped
    @secure_header: String
    @server: untyped

    @threads: Integer

    attr_accessor bind: String
    attr_reader config: Hash[String, untyped]
    attr_reader jobs: Array[String]
    attr_reader macaw_log: Logger?
    attr_accessor port: Integer
    attr_reader routes: Array[String]
    attr_accessor threads: Integer

    def delete: -> nil

    def get: -> nil

    def patch: -> nil

    def post: -> nil

    def put: -> nil

    def setup_job: -> nil

    def start!: -> nil

    private

    def extract_body: -> string

    def extract_client_info: -> nil

    def extract_headers: -> string
  end
end
