class Server
  @bind: String
  @cache: Hash[Symbol, Array]
  @context: OpenSSL::SSL::SSLContext
  @endpoints_to_cache: Array[String]
  @macaw: MacawFramework::Macaw
  @macaw_log: Logger
  @num_threads: Integer
  @port: Integer

  @prometheus: untyped
  @prometheus_middleware: untyped
  @server: TCPServer|OpenSSL::SSL::SSLServer

  @threads: Integer

  @work_queue: Thread::Queue

  @workers: Array[Thread]

  def close: -> nil

  def run: -> nil

  private

  def call_endpoint: -> Array[untyped]

  def handle_client: -> nil
end
