class Server
  @bind: String
  @macaw: MacawFramework::Macaw
  @macaw_log: Logger
  @port: Integer

  @server: TCPServer

  @threads: Integer

  def close: -> nil

  def run: -> nil

  private

  def call_endpoint: -> Array[untyped]

  def handle_client: -> nil
end
