name: Build and Publish Gem on Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-publish-gem:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Set Gem Version
        run: echo "Gem::Specification.new do |s| s.version = '$(cat lib/macaw_framework/version.rb | grep VERSION | egrep -o '[0-9]+.[0-9]+.[0-9]+')' end" > macaw_framework.gemspec
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.x
      - name: Install Dependencies
        run: bundle install
      - name: Build Gem
        run: gem build your-gemspec-file.gemspec
        env:
          GEM_VERSION: ${{ cat lib/macaw_framework/version.rb | grep VERSION | egrep -o '[0-9]+.[0-9]+.[0-9]+' }}
      - name: Publish Gem to RubyGems
        run: gem push macaw_framework-*.gem --key ${{ secrets.RUBYGEMS_API_KEY }} --host https://rubygems.org/
        env:
          GEM_VERSION: ${{ cat lib/macaw_framework/version.rb | grep VERSION | egrep -o '[0-9]+.[0-9]+.[0-9]+' }}
        if: ${{ github.ref == 'refs/heads/main' && success() }}
